alias resetbash='source ~/.bashrc'
alias editbash='sudo vim ~/.bashrc && source ~/.bashrc'
alias updatebash='sudo vim ~/.bashrc && source ~/.bashrc && cp ~/.bashrc $WINHOME/WSL_Config/bashconfig'
alias editalias='sudo vim ~/.bash_aliases && source ~/.bashrc'
alias updatealias='sudo vim ~/.bash_aliases && cp ~/.bashrc $WINHOME/WSL_Config/bash_aliases'
alias editfuncs="vim ~/.bash_functions && source ~/.bashrc"
alias editaptsource='sudo vim /etc/apt/sources.list'
alias updateaptsource='sudo vim /etc/apt/sources.list && cp /etc/apt/sources.list $WINHOME/WSL_Config/sources.list'
alias winhome='cd $WINHOME'
alias svim='sudo vim'
alias exportconfig='sudo bash $WINHOME/WSL_Config/exportConfig.sh m808752'
alias importconfig='sudo bash $WINHOME/WSL_Config/importConfig.sh m808752'
alias vim='vim -u ~/.vim/.vimrc'
alias chrome="/mnt/c/Program\ Files\ \(x86\)/Google/Chrome/Application/chrome.exe"
alias editvim='vim -u ~/.vim/.vimrc /home/m808752/.vim/.vimrc'
alias gnpm='sudo npm -g --proxy=false'
alias unpm='npm --proxy=false'
alias cls='clear'
alias open='powershell.exe /c start'
alias jumpdevnode1='ssh -J gateway2 edcdevNode1'
alias jumpprodnode1='ssh -J gateway2 edcprodNode1'
alias jumpdevnode2='ssh -J gateway2 edcdevNode2'
alias jumpprodnode2='ssh -J gateway2 edcprodNode2'
alias uur='sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y'
alias spip='sudo pip3'
alias polynote='/opt/polynote/polynote.py'
alias tmux="TERM=screen-256color-bce tmux"
